# NumPy 

NumPy stands for Numerical Python. NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

NumPy is a python library used for working with arrays.
NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

# Why Use NumPy ?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster that traditional Python lists.

Arrays are very frequently used in data science, where speed and resources are very important.


Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

#Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures


#Where is the NumPy Codebase?

The source code for NumPy is located at this github repository https://github.com/numpy/numpy

github: enables many people to work on the same codebase.


We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

#Check the version of the install numpy
print(np.__version__)

1.18.4


In [0]:
#Get help about the numpy
np?

In [0]:
#Opens the list of available functions and attributes

#np.
#np.<tab>

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays



NumPy is used to work with arrays. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

We can create a NumPy ndarray object by using the array() function.

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
my_list = [1,2,3] 
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

type(): This built-in Python function tells us the type of the object passed to it. Like in below code it shows that arr is numpy.ndarray type.


In [5]:
type(np.array(my_list))

numpy.ndarray

You can also grab the data type of the object in the array: 
arr.dtype

In [7]:
# integer array:
np.array(my_list).dtype

dtype('int64')

Remember that unlike Python lists, NumPy is constrained to arrays that all contain
the same type. If types do not match, NumPy will upcast if possible (here, integers are
upcast to floating point):

In [9]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

If we want to explicitly set the data type of the resulting array, we can use the dtype
keyword:

In [10]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)


### From a Python Tuple

We can create an array by directly converting a tuple:

In [12]:
my_tuple = (1, 2, 3, 4, 5)
np.array(my_tuple)

array([1, 2, 3, 4, 5])

#Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.


###0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.



In [16]:
print(type(42))
arr = np.array(42)
print(arr) 
print(type(arr))
print(arr.shape)

<class 'int'>
42
<class 'numpy.ndarray'>
()



###1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.



In [17]:
arr = np.array([1, 2, 3, 4, 5])
print(arr) 
print(arr.shape) 

[1 2 3 4 5]
(5,)


###2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

####NumPy has a whole sub module dedicated towards matrix operations called numpy.mat


In [19]:
arr = np.array( [ [1, 2, 3], [4, 5, 6] ] )
print(arr) 
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [20]:
my_matrix = [ [1,2,3],[4,5,6],[7,8,9] ]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [21]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [23]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the (total= 3)values 1,2,3 and 4,5,6:
arr = np.array( [ [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]] ] )

print(arr)
print(arr.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


###Check Number of Dimensions?

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [24]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([ [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]] ])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


### Higher Dimensional Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.


In [25]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

#Creating arrays from scratch
## Built-in Methods

There are lots of built-in ways to generate Arrays

In [26]:
# arange : Return evenly spaced values within a given interval.
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
# Create a length-3 float(by default) array filled with zeros
np.zeros(3)

array([0., 0., 0.])

In [30]:
# Create a length-3 integer array filled with zeros
np.zeros(3 , dtype='int')

array([0, 0, 0])

In [32]:
# Create a 3x5 floating-point array filled with zeros
np.zeros((3,5) ,  dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [33]:
# Create a length-3 floating-point array filled with 1s
np.ones(3)

array([1., 1., 1.])

In [34]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
# Create a 3x5 integer array filled with 1's
np.ones((3, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [38]:
# Create an array of three values evenly spaced between 0 and 1
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [39]:
# Create an array of 50 values evenly spaced between 0 and 10
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [41]:
#Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

In [42]:
# Create a 5x5 array of uniformly distributed
# random values between 0 and 1
np.random.random((5, 5))

array([[7.71480934e-01, 1.49638273e-01, 6.27947581e-01, 2.89656832e-01,
        2.74386167e-01],
       [7.86071078e-01, 3.83621697e-01, 7.16868642e-01, 9.42972172e-01,
        7.87232044e-01],
       [5.76011454e-01, 8.21946362e-01, 1.64521339e-01, 9.42286845e-01,
        4.02954314e-02],
       [8.25776755e-01, 6.71054944e-01, 3.18744728e-04, 6.39528801e-01,
        3.46001393e-01],
       [8.36077480e-01, 6.30965815e-01, 4.18586688e-01, 7.50482228e-01,
        8.65674238e-01]])

In [43]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3,3))

array([[-1.46520079,  1.52996697,  0.01403803],
       [ 0.09018552, -1.314373  ,  1.17689019],
       [ 1.25349991, -0.09178462, -1.04244122]])

In [44]:
# Create an 1-Dimensional array of random integers in the interval [0, 100)
# Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(1,100)

25

In [46]:
np.random.randint(1,100,10)

array([69, 63, 68, 19, 40, 59, 71, 99, 45, 92])

In [49]:
# Create a 3x3 array of random integers in the interval [0, 100)
np.random.randint(0, 100, (3, 3))

array([[38, 96, 19],
       [54, 72,  2],
       [57, 67, 12]])

In [51]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location

# uninitialized, output may vary
# the function empty creates an array whose initial content is random and depends on the state of the memory.
# By default, the dtype of the created array is float64.
np.empty(3)

array([1., 1., 1.])