# NumPy Array Attributes


In [0]:
import numpy as np

## Reshaping arrays

Reshaping means changing the shape of an array. Returns an array containing the same data with a new shape.


The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

For example, if you want to put the num‐
bers 1 through 9 in a 3×3 grid, you can do the following:


In [46]:
grid = np.arange(1, 10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array.

In [0]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [40]:
ranarr

array([47,  3, 12, 36, 40, 14, 15, 20, 35, 23])

In [48]:
# row vector via reshape
# Notice the two sets of brackets
print(arr)
print(arr.shape)
print(arr.ndim)


print(arr.reshape(1,25))
print(arr.reshape(1,25).ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)
1
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]]
2


You can do this with the reshape
method, or more easily by making use of the newaxis keyword within a slice opera‐
tion:

In [53]:
# row vector via newaxis
# arr.reshape(1,25)
arr[np.newaxis, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [54]:
# column vector via reshape
arr.reshape((25, 1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [55]:
# column vector via newaxis
#arr.reshape((25, 1))
arr[:, np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

### Reshape From 1-D to 2-D

Convert the following 1-D array with 25 elements into a 2-D array.

The outermost dimension will have 5 arrays, each with 5 elements:

In [56]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

We’ll start by defining three random
arrays: a one-dimensional, two-dimensional, and three-dimensional array. We’ll use
NumPy’s random number generator, which we will seed with a set value in order to
ensure that the same random arrays are generated each time this code is run:

In [0]:
np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

Each array has attributes ndim (the number of dimensions), shape (the size of each
dimension), and size (the total size of the array):

In [62]:
print(x1)

print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)


[5 0 3 3 7 9]
x1 ndim:  1
x1 shape: (6,)
x1 size:  6


In [63]:
print(x2)

print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)


[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12


In [64]:
print(x3)

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)


[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Another useful attribute is the dtype , the data type of the array (which we discussed previously )

In [65]:
print("x1 dtype:", x1.dtype)
print("x2 dtype:", x2.dtype)
print("x3 dtype:", x3.dtype)

x1 dtype: int64
x2 dtype: int64
x3 dtype: int64


Other attributes include itemsize , which lists the size (in bytes) of each array element, and nbytes , which lists the total size (in bytes) of the array:


In [66]:
print("x1 size (means total number of elements): ", x1.size)
print("x1 itemsize (means total number of bytes occupied by the individual element):", x1.itemsize, "bytes")
print("x1 nbytes (means total number of bytes occupied by the n elements = size * itemsize ):", x1.nbytes, "bytes")

print('\n')
print("x2 itemsize:", x2.itemsize, "bytes")
print("x2 nbytes:", x2.nbytes, "bytes")
print('\n')

print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")

x1 size (means total number of elements):  6
x1 itemsize (means total number of bytes occupied by the individual element): 8 bytes
x1 nbytes (means total number of bytes occupied by the n elements = size * itemsize ): 48 bytes


x2 itemsize: 8 bytes
x2 nbytes: 96 bytes


x3 itemsize: 8 bytes
x3 nbytes: 480 bytes


## Shape

Shape is an attribute that arrays have (not a method):

In [67]:
# Vector
arr.shape

(25,)

In [68]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
arr.reshape(1,25).shape

(1, 25)

In [70]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [71]:
arr.reshape(25,1).shape

(25, 1)