# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [3]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Also warning, but not an error instead infinity
1/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [8]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [9]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

operations are not limited to one-dimensional arrays—they can act on
multidimensional arrays as well


## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [21]:
np.random.seed(0)
values = np.random.randint(1, 10, size=5)
print(values)

[6 1 4 4 8]


In [0]:
def compute_reciprocals(values):
  output = np.empty(len(values))
  
  for i in range(len(values)):
    output[i] = 1.0 / values[i]
  return output


In [23]:
print(compute_reciprocals(values))

[0.16666667 1.         0.25       0.25       0.125     ]


In [25]:
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]


In [26]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1 loop, best of 3: 2.21 s per loop


In [27]:
%timeit (1.0 / big_array)

100 loops, best of 3: 2.76 ms per loop


Computations using vectorization through ufuncs are nearly always more efficient
than their counterpart implemented through Python loops, especially as the arrays
grow in size. Any time you see such a loop in a Python script, you should consider
whether it can be replaced with a vectorized expression.

#Exploring NumPy’s UFuncs

Ufuncs exist in two flavors: unary ufuncs, which operate on a single input, and binary
ufuncs, which operate on two inputs. We’ll see examples of both these types of func‐
tions here.

#Array arithmetic

NumPy’s ufuncs feel very natural to use because they make use of Python’s native
arithmetic operators. The standard addition, subtraction, multiplication, and division
can all be used:

In [28]:
x = np.arange(4)
print("x=",x)
print("x + 5 =", x+5)
print("x - 5 =", x-5)
print("x * 2 =", x*2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) #floor division
print("-x= ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)
print("-(0.5*x + 1) ** 2 = ", -(0.5*x + 1) ** 2 )

x= [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x=  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]
-(0.5*x + 1) ** 2 =  [-1.   -2.25 -4.   -6.25]


All of these arithmetic operations are simply convenient wrappers around specific
functions built into NumPy; for example, the + operator is a wrapper for the add
function:

In [30]:
np.add(x, 2)

array([2, 3, 4, 5])

##Arithmetic operators implemented in NumPy

    Operator Equivalent ufunc Description
    + np.add Addition (e.g., 1 + 1 = 2 )
    - np.subtract Subtraction (e.g., 3 - 2 = 1 )
    - np.negative Unary negation (e.g., -2 )
    * np.multiply Multiplication (e.g., 2 * 3 = 6 )
    / np.divide Division (e.g., 3 / 2 = 1.5 )
    // np.floor_divide Floor division (e.g., 3 // 2 = 1 )
    ** np.power Exponentiation (e.g., 2 ** 3 = 8 )
    % np.mod Modulus/remainder (e.g., 9 % 4 = 1 )

Absolute value
Just as NumPy understands Python’s built-in arithmetic operators, it also understands
Python’s built-in absolute value function:

In [31]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

The corresponding NumPy ufunc is np.absolute , which is also available under the
alias np.abs :

In [32]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [33]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [34]:
#Taking Square Ro2, 1, 0, 1, 2ots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [35]:
np.max(arr) #same as arr.max()

9

###Trigonometric functions

NumPy provides a large number of useful ufuncs, and some of the most useful for the
data scientist are the trigonometric functions. We’ll start by defining an array of
angles:

In [36]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

#Exponents and logarithms

Another common type of operation available in a NumPy ufunc are the exponentials:

In [37]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [38]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [39]:
x = [1, 2, 3]
print("x=", x)
print("e^x=", np.exp(x))
print("2^x=", np.exp2(x))
print("3^x=", np.power(3, x))

x= [1, 2, 3]
e^x= [ 2.71828183  7.3890561  20.08553692]
2^x= [2. 4. 8.]
3^x= [ 3  9 27]


The inverse of the exponentials, the logarithms, are also available. The basic np.log
gives the natural logarithm; if you prefer to compute the base-2 logarithm or the
base-10 logarithm, these are available as well:

In [40]:
x = [1, 2, 4, 10]
print("x=",x)

print("ln(x)=",np.log(x))
print("log2(x) =",np.log2(x))
print("log10(x) =",np.log10(x))

x= [1, 2, 4, 10]
ln(x)= [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


There are also some specialized versions that are useful for maintaining precision
with very small input:

In [41]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


When x is very small, these functions give more precise values than if the raw np.log
or np.exp were used.

## Advanced Ufunc Features

Many NumPy users make use of ufuncs without ever learning their full set of features.
We’ll outline a few specialized features of ufuncs here.


#Specifying output


For large calculations, it is sometimes useful to be able to specify the array where the
result of the calculation will be stored. Rather than creating a temporary array, you
can use this to write computation results directly to the memory location where you’d like them to be. For all ufuncs, you can do this using the out argument of the
function:

In [42]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(x)
print(y)

[0 1 2 3 4]
[ 0. 10. 20. 30. 40.]


#Summing the Values in an Array

As a quick example, consider computing the sum of all values in an array. Python
itself can do this using the built-in sum function:


In [43]:
L = np.random.random(100)
sum(L)

50.461758453195614

The syntax is quite similar to that of NumPy’s sum function, and the result is the same
in the simplest case:

In [44]:
np.sum(L)

50.46175845319564

However, because it executes the operation in compiled code, NumPy’s version of the
operation is computed much more quickly:

In [45]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

10 loops, best of 3: 160 ms per loop
1000 loops, best of 3: 383 µs per loop


In [0]:
%timeit np.sum(big_array)

Be careful, though: the sum function and the np.sum function are not identical, which
can sometimes lead to confusion! In particular, their optional arguments have differ‐
ent meanings, and np.sum is aware of multiple array dimensions

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [46]:
ranarr = np.random.randint(0,50,10)
ranarr

array([32, 33, 29, 41, 19, 11, 19,  7, 36, 10])

In [47]:
ranarr.max()

41

In [48]:
ranarr.argmax()

3

In [49]:
ranarr.min()

7

In [50]:
ranarr.argmin()

7

In [51]:
%timeit min(big_array)
%timeit np.min(big_array)

10 loops, best of 3: 118 ms per loop
1000 loops, best of 3: 417 µs per loop


#Other aggregation functions

NumPy provides many other aggregation functions, but we won’t discuss them in
detail here. Additionally, most aggregates have a NaN -safe counterpart that computes the result while ignoring missing values, which are marked by the special IEEE
floating-point NaN value 


    Aggregation functions available in NumPy
    Function Name NaN-safe Version np.sum np.nansum Description
    Compute sum of elements
    np.prod np.nanprod Compute product of elements
    np.mean np.nanmean Compute median of elements
    np.std np.nanstd Compute standard deviation
    np.var np.nanvar Compute variance
    np.min np.nanmin Find minimum value
    np.max np.nanmax Find maximum value
    np.argmin np.nanargmin Find index of minimum value
    np.argmax np.nanargmax Find index of maximum value
    np.median np.nanmedian Compute median of elements
    np.percentile np.nanpercentile Compute rank-based statistics of elements
    np.any N/A Evaluate whether any elements are true
    np.all N/A Evaluate whether all elements are true
